model_path: 
model_family: phi

use_lora: True
save_dir: 
dataset: PII
forget_loss: grad_ascent

# ## PII thing
# data_path: [data/test,data/test, data/test, data/test, data/PII, data/PII, data/test]
# #data_path: [data/test]

# ### The PII set thing
# split: forget10
# split_list:
#   - test_retain_pii
#   - test_retain_pii
#   - real_authors_perturbed
#   - world_facts_perturbed
#   - ${split}
#   - ${split}
#   - test_retain_pii


# question_key: [question, question, question, question, paraphrased_question, paraphrased_question, None]
# answer_key: [answer, answer, answer, answer, answer, answer, None]
# base_answer_key: [paraphrased_answer, answer, answer, paraphrased_answer, paraphrased_answer, paraphrased_answer, None]
# perturbed_answer_key: [perturbed_answer, perturbed_answer, perturbed_answer, perturbed_answer, perturbed_answer, perturbed_answer, None]
# eval_task: [eval_log_retain, eval_real_author_wo_options, eval_real_world_wo_options, eval_log_forget, eval_log_forget_rephrase, eval_log_retain_rephrase, extraction_attack]



data_path: [data/test, data/test, data/test, data/test, data/test, data/PII, data/PII, data/PII, data/PII, data/PII, data/PII,data/test,data/test,data/test,data/test,data/test]

split: forget10
split_list:
  - test_retain_pii
  - real_authors_perturbed
  - world_facts_perturbed
  - ${split}
  - test_retain_pii
  - ${split}
  - ${split}
  - ${split}
  - ${split}
  - ${split}
  - test_retain_pii
  - test_retain_pii
  - test_retain_pii
  - test_retain_pii
  - test_retain_pii
  - ${split}

question_key: [question, question, question, question, null, paraphrased_question_1, paraphrased_question_2, paraphrased_question_3, paraphrased_question_4, paraphrased_question_5,paraphrased_question_1, paraphrased_question_2, paraphrased_question_3, paraphrased_question_4, paraphrased_question_5, inverted_question]
answer_key: [answer, answer, answer, answer, null, paraphrased_answer_1, paraphrased_answer_2, paraphrased_answer_3, paraphrased_answer_4, paraphrased_answer_5,paraphrased_answer_1, paraphrased_answer_2, paraphrased_answer_3, paraphrased_answer_4, paraphrased_answer_5, inverted_answer]
base_answer_key: [answer, answer, answer, answer, null, paraphrased_answer_1, paraphrased_answer_2, paraphrased_answer_3, paraphrased_answer_4, paraphrased_answer_5, paraphrased_answer_1, paraphrased_answer_2, paraphrased_answer_3, paraphrased_answer_4, paraphrased_answer_5, inverted_answer]
perturbed_answer_key: [perturbed_answer_1, perturbed_answer, perturbed_answer, perturbed_answer_1, null, perturbed_answer_1, perturbed_answer_2, perturbed_answer_3, perturbed_answer_4, perturbed_answer_5, perturbed_answer_1, perturbed_answer_2, perturbed_answer_3, perturbed_answer_4, perturbed_answer_5,null]
eval_task: [eval_log_retain, eval_real_author_wo_options, eval_real_world_wo_options, eval_log_forget, extraction_attack, eval_log_forget_paraphrase_1, eval_log_forget_paraphrase_2, eval_log_forget_paraphrase_3, eval_log_forget_paraphrase_4, eval_log_forget_paraphrase_5,eval_log_retain_paraphrase_1, eval_log_retain_paraphrase_2, eval_log_retain_paraphrase_3, eval_log_retain_paraphrase_4, eval_log_retain_paraphrase_5, eval_log_retain_indirect]


generation:
  max_length: 200
  max_new_tokens: 128

save_generated_text: true

ds_size: null 
bf16: false

overwrite: true
use_pretrained: false

batch_size: 30
reinitialize_weights: false
retain_result: null

