model_path: 
model_family: phi

use_lora: false
save_dir: 
dataset: PII
forget_loss: grad_ascent
split_person_name_path: '/projects/0/hpmlprjs/LLM/danp/UGBench/data/PII/split_person_names'
split: forget10

data_path: [data/PII]
split_list:
  - ${split}

question_key: [null]
answer_key: [null]
base_answer_key: [null]
perturbed_answer_key: [null]
eval_task: [extraction_attack]


generation:
  max_length: 200
  max_new_tokens: 128
  do_sample: false

save_generated_text: true

ds_size: null 
bf16: false

overwrite: true
use_pretrained: false

batch_size: 30
reinitialize_weights: false
retain_result: null