model_path: 
model_family: phi

use_lora: False
save_dir: 
dataset: PII
forget_loss: grad_ascent
split_person_name_path: '/projects/0/hpmlprjs/LLM/danp/UGBench/data/PII/split_person_names'


data_path: [data/PII, data/test, data/test, data/test, data/PII, data/PII,data/test, data/PII,data/test]
split: forget10
split_list:
  - ${split}
  - test_retain_pii
  - real_authors_perturbed
  - world_facts_perturbed
  - ${split}
  - ${split}
  - test_retain_pii
  - ${split}
  - test_retain_pii

question_key: [null, question, question, question, question, paraphrased_question_1,paraphrased_question_1, inverted_question,inverted_question]
answer_key: [null, answer, answer, answer, answer, paraphrased_answer_1,paraphrased_answer_1, inverted_answer,inverted_answer]
base_answer_key: [null, paraphrased_answer_1, answer, answer, paraphrased_answer_1, paraphrased_answer_1,paraphrased_answer_1, inverted_answer,inverted_answer]
perturbed_answer_key: [null, perturbed_answer_1, perturbed_answer, perturbed_answer, perturbed_answer_1, perturbed_answer_1,perturbed_answer_1, inverted_answer,inverted_answer]
eval_task: [one_hop_attack, eval_log_retain, eval_real_author_wo_options, eval_real_world_wo_options, eval_log_forget, eval_log_forget_paraphrase_1,eval_log_retain_paraphrase_1, eval_log_forget_inverse,eval_log_retain_inverse]



generation:
  max_length: 200
  max_new_tokens: 128
  do_sample: false

save_generated_text: true

ds_size: null 
bf16: false

overwrite: true
use_pretrained: false

batch_size: 30
reinitialize_weights: false
retain_result: null

