model_path: 
model_family: phi

use_lora: True
save_dir: 
dataset: PII
forget_loss: grad_ascent
split_person_name_path: '/projects/0/hpmlprjs/LLM/danp/UGBench/data/PII/split_person_names'



data_path: [data/PII]
split: forget10
split_list:
  - ${split}

question_key: [null]
answer_key: [null]
base_answer_key: [null]
perturbed_answer_key: [null]
eval_task: [extraction_attack]

# data_path: [data/PII, data/test]
# split: forget10
# split_list:
#   - ${split}
#   - test_retain_pii
# question_key: [question, question]
# answer_key: [answer, answer]
# base_answer_key: [paraphrased_answer_5, paraphrased_answer_1]
# perturbed_answer_key: [perturbed_answer_1, perturbed_answer_1]
# eval_task: [eval_log_forget, eval_log_retain]



generation:
  max_length: 200
  max_new_tokens: 128

save_generated_text: true

ds_size: null 
bf16: false

overwrite: true
use_pretrained: false

batch_size: 30
reinitialize_weights: false
retain_result: null