model_path: 
model_family: phi

use_lora: True
save_dir: 
dataset: PII
forget_loss: grad_ascent

## PII thing
#data_path: [data/test, data/test, data/test, data/TOFU, data/TOFU, data/test]

data_path: [data/test, data/test, data/test, data/PII, data/PII, data/test]


### The PII set thing
split: forget10
split_list:
  - test_retain_pii
  - real_authors_perturbed
  - world_facts_perturbed
  - ${split}
  - ${split}
  - test_retain_pii


question_key: [question, question, question, question, paraphrased_question, paraphrased_question]
answer_key: [answer, answer, answer, answer, answer, answer]
base_answer_key: [paraphrased_answer, answer, answer, paraphrased_answer, paraphrased_answer, paraphrased_answer]
perturbed_answer_key: [perturbed_answer, perturbed_answer, perturbed_answer, perturbed_answer, perturbed_answer, perturbed_answer]

eval_task: [eval_log_retain, eval_real_author_wo_options, eval_real_world_wo_options, eval_log_forget, eval_log_forget_rephrase, eval_log_retain_rephrase]




generation:
  max_length: 200
  max_new_tokens: null

save_generated_text: true

ds_size: null 

bf16: false

overwrite: true
use_pretrained: false

batch_size: 30
reinitialize_weights: false

retain_result: null

