model_path: 
model_family: phi

use_lora: True
save_dir: 
dataset: PII
forget_loss: grad_ascent
split_person_name_path: '/projects/0/hpmlprjs/LLM/danp/UGBench/data/PII/split_person_names'
random_split: 1
data_path: 
    - "data/test"
    - "data/PII/SplitExperiment/Experiment${random_split}"
    - "data/PII/SplitExperiment/Experiment${random_split}"
    - "data/test"


split: forget10
split_list:
  - test_retain_pii
  - ${split}
  - ${split}
  - test_retain_pii

question_key: [question, question, paraphrased_question_1, paraphrased_question_1]
answer_key: [answer, answer, paraphrased_answer_1, paraphrased_answer_1]
base_answer_key: [paraphrased_answer_1, paraphrased_answer_1, paraphrased_answer_1, paraphrased_answer_1]
perturbed_answer_key: [perturbed_answer_1, perturbed_answer_1, perturbed_answer_1, perturbed_answer_1]
eval_task: [eval_log_retain, eval_log_forget, eval_log_forget_paraphrase_1, eval_log_retain_paraphrase_1]

generation:
  max_length: 200
  max_new_tokens: 128

save_generated_text: true

ds_size: null 
bf16: false

overwrite: true
use_pretrained: false

batch_size: 30
reinitialize_weights: false
retain_result: null

