model_family: llama2-7b
project_name: 
run_name: 
log_dir: /run_logs

LoRA:
  r: 0
  alpha: 32
  dropout: 0.05

dataset: TOFU
#data_path: /projects/0/hpmlprjs/LLM/danp/UGBench/data/TOFU/retain99.json
data_path: locuslab/TOFU

split: full
batch_size: 16
gradient_accumulation_steps: 1
num_epochs: 5
lr: 1e-5
bf16: true
save_dir: ./output/ft_epoch${num_epochs}_lr${lr}_${model_family}_${split}_wd${weight_decay}

weight_decay: 0.01
seed: 42

ds_size: null