use_lora: false  
use_quantization: false
log_dir: /run_logs
project_name: 
run_name: 
split_person_name_path: '/projects/0/hpmlprjs/LLM/danp/UGBench/data/PII/split_person_names'


model_family: phi
model_path: null
LoRA:
  r: 256
  alpha: 512
  dropout: 0.05
  bias: none
  task_type: CAUSAL_LM

lr: 1e-5
dataset: Harry
split: forget
forget_data_path: /data/PII  
retain_data_path: /data/PII
batch_size: 4 
gradient_accumulation_steps: 4
num_epochs: 5
enable_neftune_noise: false

forget_loss: grad_ascent 


save_dir: outputs
overwrite_dir: true # false
weight_decay: 0.01
save_model: true
eval_while_train: false
eval_only: false
seed: 42
cache_dir: cache

bf16: true
retain_weight: 1

C: 0.1
P: 0.4


#### NEW PERMU IN TEXT ADDITION STUFF
in_text : false # Indicator for PerMU discrete token undlearning, so used only when forget_loss is set to PerMU
token_replace_prob : 0.6
token_k_neighbours : 1
subject_noise_discrepancy_addition: false
subject_key: 'subject'


optimal_neighbours_generation: false
use_adaptive_k: false
match_first_char: false


eval:
  # retain_result: data/retain90_llama_wd0.01/eval_results/ds_size300/eval_log_aggregated.json
  model_path: ${..model_path}
  model_family: ${..model_family}
  save_dir: ${..save_dir}
  data_path: [data/test, data/test, data/test, data/test, data/test, data/PII, data/PII, data/PII, data/PII, data/PII, data/PII]

  split: forget10
  split_list:
    - test_retain_pii
    - real_authors_perturbed
    - world_facts_perturbed
    - ${split}
    - test_retain_pii
    - ${split}
    - ${split}
    - ${split}
    - ${split}
    - ${split}

  question_key: [question, question, question, question, None, paraphrased_question_1, paraphrased_question_2, paraphrased_question_3, paraphrased_question_4, paraphrased_question_5, inverted_question]
  answer_key: [answer, answer, answer, answer, None, paraphrased_answer_1, paraphrased_answer_2, paraphrased_answer_3, paraphrased_answer_4, paraphrased_answer_5, inverted_answer]
  base_answer_key: [paraphrased_answer, answer, answer, paraphrased_answer, None, paraphrased_answer_1, paraphrased_answer_2, paraphrased_answer_3, paraphrased_answer_4, paraphrased_answer_5, inverted_answer]
  perturbed_answer_key: [perturbed_answer, perturbed_answer, perturbed_answer, perturbed_answer, None, perturbed_answer_1, perturbed_answer_2, perturbed_answer_3, perturbed_answer_4, perturbed_answer_5, None]
  eval_task: [eval_log_retain, eval_real_author_wo_options, eval_real_world_wo_options, eval_log_forget, extraction_attack, eval_log_forget_paraphrase_1, eval_log_forget_paraphrase_2, eval_log_forget_paraphrase_3, eval_log_forget_paraphrase_4, eval_log_forget_paraphrase_5, eval_log_forget_indirect]


  generation:
    max_length: 200
    max_new_tokens: null

  save_generated_text: true

  ds_size: 300

  overwrite: true
  use_pretrained: false

  batch_size: 30
  retain_result: null



# ADD THIS HYDRA CONFIGURATION SECTION
defaults:
  - _self_

hydra:
  job:
    name: ${forget_loss}_${model_family}_B${batch_size}_G${gradient_accumulation_steps}
    chdir: false
  
  run:
    dir: ${save_dir}/hydra_logs/${forget_loss}/${now:%Y-%m-%d}/${now:%H-%M-%S}

# In your forget_pii.yaml
logging:
  time_stats: false
  padding_stats: false
  entropy_stats: false
  subject_token_len : false
  log_every_n: 100
  corrupted_subjects: false
  permu_contrast_stats: false