llama2-7b:
  hf_key: "NousResearch/Llama-2-7b-chat-hf"
  question_start_tag: "[INST] "
  question_end_tag: " [/INST]"
  answer_tag: ""
  flash_attention2: "false"   
  gradient_checkpointing: "true"
  # this model will be used for unlearning by default
  tofu_target_model_path: "locuslab/tofu_ft_llama2-7b" 
  harry_target_model_path: "Maybe1407/harry_llama7b_to_unlearn" 
  zsre_target_model_path: "Maybe1407/zsre_llama7b_to_unlearn"
phi:
  hf_key: "microsoft/phi-1_5"
  question_start_tag: "Question: "
  question_end_tag: "\n"
  answer_tag: "Answer: "
  flash_attention2: "false"
  gradient_checkpointing: "false"
  tofu_target_model_path: "locuslab/tofu_ft_phi-1.5"
  harry_target_model_path: "Maybe1407/harry_phi_to_unlearn"
  zsre_target_model_path: "Maybe1407/zsre_phi_to_unlearn"


  
